//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCI_2024.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCI_2024.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Item.
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all fields..
        /// </summary>
        internal static string AddItemFailMessage {
            get {
                return ResourceManager.GetString("AddItemFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Movie.
        /// </summary>
        internal static string AddMovie {
            get {
                return ResourceManager.GetString("AddMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in all fields..
        /// </summary>
        internal static string AddMovieFailMessage {
            get {
                return ResourceManager.GetString("AddMovieFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Showing.
        /// </summary>
        internal static string AddShowing {
            get {
                return ResourceManager.GetString("AddShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid movie title and price..
        /// </summary>
        internal static string AddShowingFailMessage {
            get {
                return ResourceManager.GetString("AddShowingFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        internal static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID and PIN must be 4 digits long..
        /// </summary>
        internal static string AddUserFailMessage {
            get {
                return ResourceManager.GetString("AddUserFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Added.
        /// </summary>
        internal static string AdminAdded {
            get {
                return ResourceManager.GetString("AdminAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier ID.
        /// </summary>
        internal static string CashierID {
            get {
                return ResourceManager.GetString("CashierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change PIN.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN change failed..
        /// </summary>
        internal static string ChangePasswordFail {
            get {
                return ResourceManager.GetString("ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN changed successfully..
        /// </summary>
        internal static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item.
        /// </summary>
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Movie.
        /// </summary>
        internal static string DeleteMovie {
            get {
                return ResourceManager.GetString("DeleteMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Showing.
        /// </summary>
        internal static string DeleteShowing {
            get {
                return ResourceManager.GetString("DeleteShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        internal static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drinks.
        /// </summary>
        internal static string Drinks {
            get {
                return ResourceManager.GetString("Drinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order is empty!.
        /// </summary>
        internal static string EmptyOrder {
            get {
                return ResourceManager.GetString("EmptyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string ExitQuestion {
            get {
                return ResourceManager.GetString("ExitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input.
        /// </summary>
        internal static string InvalidInput {
            get {
                return ResourceManager.GetString("InvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Added.
        /// </summary>
        internal static string ItemAdded {
            get {
                return ResourceManager.GetString("ItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Admin.
        /// </summary>
        internal static string MakeAdmin {
            get {
                return ResourceManager.GetString("MakeAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Added.
        /// </summary>
        internal static string MovieAdded {
            get {
                return ResourceManager.GetString("MovieAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Name.
        /// </summary>
        internal static string MovieName {
            get {
                return ResourceManager.GetString("MovieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number of tickets:.
        /// </summary>
        internal static string NumOfTickets {
            get {
                return ResourceManager.GetString("NumOfTickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        internal static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture URL.
        /// </summary>
        internal static string PictureUrl {
            get {
                return ResourceManager.GetString("PictureUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN.
        /// </summary>
        internal static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster URL.
        /// </summary>
        internal static string PosterUrl {
            get {
                return ResourceManager.GetString("PosterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        internal static string Receipts {
            get {
                return ResourceManager.GetString("Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        internal static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select date.
        /// </summary>
        internal static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Movie.
        /// </summary>
        internal static string SelectMovie {
            get {
                return ResourceManager.GetString("SelectMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Showing.
        /// </summary>
        internal static string SelectShowing {
            get {
                return ResourceManager.GetString("SelectShowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Time.
        /// </summary>
        internal static string SelectTime {
            get {
                return ResourceManager.GetString("SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        internal static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing Added.
        /// </summary>
        internal static string ShowingAdded {
            get {
                return ResourceManager.GetString("ShowingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snacks.
        /// </summary>
        internal static string Snacks {
            get {
                return ResourceManager.GetString("Snacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Added.
        /// </summary>
        internal static string UserAdded {
            get {
                return ResourceManager.GetString("UserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Receipts.
        /// </summary>
        internal static string ViewReceipts {
            get {
                return ResourceManager.GetString("ViewReceipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
